packages:
- .

extra-deps:
- recursion-schemes-5.2.2.2
- base-orphans-0.8.7
- comonad-5.0.8
- data-fix-0.3.2
- free-5.1.9
- th-abstraction-0.4.4.0
- distributive-0.6.2.1
- hashable-1.4.1.0
- indexed-traversable-0.1.2
- profunctors-5.6.2
- semigroupoids-5.3.7
- tagged-0.8.6.1
- transformers-base-0.4.6
- transformers-compat-0.7.2
- bifunctors-5.5.12
- contravariant-1.5.5
- unordered-containers-0.2.19.1
- StateVar-1.2.2


resolver:
  compiler: ghc-8.10.7
